---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

matrix:
  - name: markdown
    dictionary:
      wordlists:
        - .github/.wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.url:
    sources:
      - '**/*.md'
    aspell:
      lang: en
      ignore-case: true
